from cuten import tensor, Tensor
from cuten.engine import cuda
import cuten
import timeit


start = timeit.default_timer()
print("----------Tensor:a----------")
a = tensor([[[1,2,3,4],[5,6,7,8]],[[1,4,9,16],[25,36,49,64]]], dtype=cuten.uchar, device="cuda:0")
print(a)
print(type(a))
print(a.sizeof())
print(a.shape())
print(a.device)
print(a.numel())
print(a.numpy())
print(a.pointer())

print("----------Tensor:b----------")
b = tensor([1,2,3,4,5,6], dtype=cuten.uint64, device="cuda:0", lazy=True)
print(b)
print(b.sizeof())
print(b.shape())
print(b.device)
print(b.numel())
print(b.numpy())
print(b.pointer())

print("----------Tensor:c----------")
c = tensor(2, dtype=cuten.uint64, device="cuda:0", lazy=True)
print(c)
print(c.sizeof())
print(c.shape())
print(c.device)
print(c.numel())
print(c.numpy())
print(c.pointer())

print("----------Tensor:d----------")
d = tensor([[[2]]], dtype=cuten.uint64, device="cuda:0", lazy=True)
print(d)
print(d.sizeof())
print(d.shape())
print(d.device)
print(d.numel())
print(d.numpy())
print(d.pointer())

print("----------Tensor:e----------")
e = a.astype(cuten.longlong)
print(e)
print(e.sizeof())
print(e.shape())
print(e.device)
print(e.numel())
print(e.numpy())
print(e.pointer())

print("----------Tensor:f----------")
f = b.astype(cuten.complex128)
print(f)
print(f.sizeof())
print(f.shape())
print(f.device)
print(f.numel())
print(f.numpy())
print(f.pointer())

g = f.astype(cuten.complex64)
print(g)

print("----------Tensor:1:cpu----------")
ones = Tensor.ones((2,2,4))
print(ones)
print(ones.sizeof())
print(ones.shape())
print(ones.device)
print(ones.numel())
print(ones.numpy())
print(ones.pointer())

print("----------Tensor:1:cuda----------")
cuones = Tensor.ones((2,2,4), device="cuda:0")
print(cuones)
print(cuones.sizeof())
print(cuones.shape())
print(cuones.device)
print(cuones.numel())
print(cuones.numpy())
print(cuones.pointer())

print("----------Tensor:0:cpu----------")
zeros = Tensor.zeros((2,2,4))
print(zeros)
print(zeros.sizeof())
print(zeros.shape())
print(zeros.device)
print(zeros.numel())
print(zeros.numpy())
print(zeros.pointer())

print("----------Tensor:0:cuda----------")
cuzeros = Tensor.zeros((2,2,4), device="cuda:0")
print(cuzeros)
print(cuzeros.sizeof())
print(cuzeros.shape())
print(cuzeros.device)
print(cuzeros.numel())
print(cuzeros.numpy())
print(cuzeros.pointer())

print("----------Tensor:fill:cpu----------")
fill = Tensor.fill(1j, (2,2,4))
print(fill)
print(fill.sizeof())
print(fill.shape())
print(fill.device)
print(fill.numel())
print(fill.numpy())
print(fill.pointer())

print("----------Tensor:fill:cuda----------")
cufill = Tensor.fill(1j, (2,2,4), device="cuda:0")
print(cufill)
print(cufill.sizeof())
print(cufill.shape())
print(cufill.device)
print(cufill.numel())
print(cufill.numpy())
print(cufill.pointer())

print("----------Clone-----------")
clone = a.clone()
print(clone)
print(clone.sizeof())
print(clone.shape())
print(clone.device)
print(clone.numel())
print(clone.numpy())
print(clone.pointer())

print("----------Tensor:make-lazy----------")
o = Tensor([1,False,3.90,1+2j], device="cuda:0")
print(o)
print(o.lazy())
print(o.lazy())

print("----------Tensor:make-eager----------")
p = Tensor(2, device="cuda:0").lazy()
print(p)
print(p.eager())

print("----------Tensor:getters----------")
e = Tensor([[1,2,3],[4,5,6]], device="cuda:0")
print(e[0])

print("----------Tensor:setters----------")
f = Tensor([[1,2,3],[4,5,6]], device="cuda:0")
f[0] = [4,5,6]
print(f.numpy())

end = timeit.default_timer()

print("----------Time-----------")
print(end - start)

print("----------CUDA:func-----------")
print(cuda.get_device_name(0))
print(cuda.current_device())
print(cuda.get_arch_list())
