from typing import Any, Type, List
from ..dtypes import Fmts
import ctypes


def s_toCPU(scalar:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def s_fromCPU(pointer:ctypes.c_void_p, fmt:Fmts) -> Type: ...
def v_toCPU(array1D:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def v_fromCPU(pointer:ctypes.c_void_p, length:int, fmt:Fmts) -> List[Any]: ...
