from typing import Union, List, Any
from ..dtypes import Fmts
import ctypes

Scalars = Union[int, float, complex, bool]
Vectors = List[Scalars]

def s_toCPU(scalar:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def s_fromCPU(pointer:ctypes.c_void_p, fmt:Fmts) -> Scalars: ...
def v_toCPU(array1D:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def v_fromCPU(pointer:ctypes.c_void_p, length:int, fmt:Fmts) -> Vectors: ...
