from typing import List, Any
from ..dtypes import Fmts
import ctypes


def s_toCUDA(scalar:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def s_fromCUDA(pointer:ctypes.c_void_p, fmt:Fmts) -> Any: ...
def s_toHost(pointer:ctypes.c_void_p, fmt:Fmts) -> ctypes.c_void_p: ...
def v_toCUDA(array1D:List[Any], fmt:Fmts) -> ctypes.c_void_p: ...
def v_fromCUDA(pointer:ctypes.c_void_p, length:int, fmt:Fmts) -> List[Any]: ...
def v_toHost(pointer:ctypes.c_void_p, length:int, fmt:Fmts) -> ctypes.c_void_p: ...
