from typing import Union, List, Any
from ..dtypes import Fmts
import ctypes

Scalars = Union[int, float, complex, bool]
Vectors = List[Scalars]

def s_toCUDA(scalar:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def s_fromCUDA(pointer:ctypes.c_void_p, fmt:Fmts) -> Scalars: ...
def s_toHost(pointer:ctypes.c_void_p, fmt:Fmts) -> ctypes.c_void_p: ...
def v_toCUDA(array1D:Any, fmt:Fmts) -> ctypes.c_void_p: ...
def v_fromCUDA(pointer:ctypes.c_void_p, length:int, fmt:Fmts) -> Vectors: ...
def v_toHost(pointer:ctypes.c_void_p, length:int, fmt:Fmts) -> ctypes.c_void_p: ...
