from typing import Dict, List, Union
import ctypes

def count() -> int: ...
def get_prop(device_id:int=0) -> Dict: ...
def tocuda(pyobject:Union[ctypes.c_void_p,List], device_id:int, numel:int, fmt:str) -> ctypes.c_void_p: ...
def tocpu(pyobject, numel:int, fmt:str) -> ctypes.c_void_p: ...
def data(pyobject, numel:int, fmt:str) -> List: ...
