from typing import Any
from tenop.helpers import Scalar, TensorType

def reduce_max_bool(pointer:Any, length:int) -> Scalar: ...
def reduce_max_char(pointer:Any, length:int) -> Scalar: ...
def reduce_max_uchar(pointer:Any, length:int) -> Scalar: ...
def reduce_max_short(pointer:Any, length:int) -> Scalar: ...
def reduce_max_ushort(pointer:Any, length:int) -> Scalar: ...
def reduce_max_int(pointer:Any, length:int) -> Scalar: ...
def reduce_max_uint(pointer:Any, length:int) -> Scalar: ...
def reduce_max_long(pointer:Any, length:int) -> Scalar: ...
def reduce_max_ulong(pointer:Any, length:int) -> Scalar: ...
def reduce_max_longlong(pointer:Any, length:int) -> Scalar: ...
def reduce_max_ulonglong(pointer:Any, length:int) -> Scalar: ...
def reduce_max_float(pointer:Any, length:int) -> Scalar: ...
def reduce_max_double(pointer:Any, length:int) -> Scalar: ...
def reduce_max_longdouble(pointer:Any, length:int) -> Scalar: ...
def reduce_min_bool(pointer:Any, length:int) -> Scalar: ...
def reduce_min_char(pointer:Any, length:int) -> Scalar: ...
def reduce_min_uchar(pointer:Any, length:int) -> Scalar: ...
def reduce_min_short(pointer:Any, length:int) -> Scalar: ...
def reduce_min_ushort(pointer:Any, length:int) -> Scalar: ...
def reduce_min_int(pointer:Any, length:int) -> Scalar: ...
def reduce_min_uint(pointer:Any, length:int) -> Scalar: ...
def reduce_min_long(pointer:Any, length:int) -> Scalar: ...
def reduce_min_ulong(pointer:Any, length:int) -> Scalar: ...
def reduce_min_longlong(pointer:Any, length:int) -> Scalar: ...
def reduce_min_ulonglong(pointer:Any, length:int) -> Scalar: ...
def reduce_min_float(pointer:Any, length:int) -> Scalar: ...
def reduce_min_double(pointer:Any, length:int) -> Scalar: ...
def reduce_min_longdouble(pointer:Any, length:int) -> Scalar: ...
